# Generated by Django 3.0 on 2022-06-06 07:25

import app_layer.behavioural.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_layer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskID', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=100, validators=[app_layer.behavioural.validators.validate_name])),
                ('taskCreatedOn', models.DateField(auto_now_add=True, validators=[app_layer.behavioural.validators.validate_date])),
                ('taskDescription', models.CharField(blank=True, max_length=250, validators=[app_layer.behavioural.validators.validate_empDescription])),
                ('taskOrg', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='empTask',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_layer.Task'),
        ),
    ]
