# Generated by Django 3.0 on 2022-06-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_layer', '0002_auto_20220606_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskCreatedOn',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskDescription',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskName',
            field=models.CharField(max_length=100),
        ),
    ]
